### ISSUE TITLE
Client display error in multiplayer

### ISSUE THREAD

**Issue by CuiZhenhang** [Nernar/Minimap#2]
English:
In multiplayer, the minimap for clients in the local world works fine, but the minimap for clients joining the remote world is completely transparent except for the icon representing itself.
InnerCore package version b113, use WLAN connection.

中文：
在多人游戏中，在本地世界的客户端的小地图工作正常，但加入远程世界的客户端的小地图除表示自己的图标外完全透明。
InnerCore 包版本 b113，使用无线局域网联机。

**Comment by ichackathon** [comment]
@CuiZhenhang I've fixed issues with map rendering in multiplayer, however I need some more information. Install Minimap from latest commit and attach a small demo snippet of recorded fix if it worked for you.
