### ISSUE TITLE
Minimap automatically opens when minimized

### ISSUE THREAD

**Issue by CuiZhenhang** [Nernar/Minimap#3]
English:
After minimizing the minimap, the minimap will automatically open when the GUI is changed to the "in_game_play_screen".
But it should have been minimized.
中文：
在最小化小地图后，当GUI被改变至 "in_game_play_screen" 时，小地图会自动打开。
但它本应该最小化。

**Comment by rislaed** [comment]
Yeah, it's not a bug, it's **feature**. Thank you so much for feedback, I'll review it as soon as possible.
